### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [AlexanderKuptsov/TheBestCubikRubik#1]
1. Из операций в задании у вас реализован пока поворот одного слоя любой грани, прочитайте ещё раз текст задания.
2. Выбор грани для поворота с помощью целого числа - не самое удачное решение для интерфейса класса. Используйте перечисления.
3. Ваш метод случайной установки состояния кубика может сгенерировать (и почти всегда сгенерирует) состояние, противоречащее физической модели кубика Рубика. Например (в случае 3х3), грань с красным центром всегда должна находиться напротив грани с оранжевым центром, к одному ребру не могут прилегать в одном месте красный и оранжевый квадрат и т. п. Даже пренебрегая этим, ваш алгоритм может сгенерировать вообще несобираемый кубик (если у вас есть физический кубик, попробуйте вынуть элемент из центра грани и вставить его, перевернув). Подумайте, как корректно "перемешать" кубик Рубика. Как вы это делаете с физическим кубиком?
4. Возможно следует вынести функциональность перемешивания кубика из конструктора в отдельный метод `shuffle` и сделать так, чтобы конструктор создавал собранный кубик.
5. Ваши методы поворота не переносимы на кубики размера, отличного от 3. Самый простой (но не самым эффективный способ)  - повернуть весь кубик так, чтобы поворачивать нужно было только, например, переднюю грань.

**Comment by AlexanderKuptsov** [comment]
1. Добавил поворот указанного числа слоев направо/налево для главной грани (передняя грань).
2. Добавил перечисления для направления и для граней.
3. Добавил метод shuffle, и конструктор теперь создает собранный кубик.

**Comment by gagarski** [comment]
1. Перечисления-то вы добавили, но в параметрах методов у вас по-прежнему целые числа
2. Помните, что цель данного задания -- реализовать класс, представляющий кубик Рубика и предоставляющий интерфейс для работы с ним. У вашего класса все методы приватные (кроме `toString`, которого нельзя сделать приватным)
3. Обилие методов для поворота немного смущает: хотелось бы видеть один публичный метод, которому можно задать:
     - направление поворота (в виде объекта перечисления)
     - поворачиваемую сторону (в виде объекта перечисления)
     - список (или массив) поворачиваемых граней
    Два метода (для разных направлений) -- допустимый вариант. Можете реализовать некоторое число приватных вспомогательных методов и реализовать публичный через них. Например поворот *любой* стороны может быть реализован как 
     - поворот всего кубика так, чтобы поворачиваемая сторона была фронтальной
     - поворот заданных граней фронтальной стороны в заданном направлении
     - обратный поворот всего кубика

**Comment by AlexanderKuptsov** [comment]
Добавил перечисление в 1 метод (вместо числа).  В одном методе (rightSwipe) все еще требуется число (numberOfRotations). Оно задает нужное количество поворотов всего кубика.
Метод rotationMain (теперь public)- главный метод ( повороты фронтальной стороны).
Методы (вспомогательные) rightSwipe и upDownSwipe делают любую сторону фронтальной, а после выполнения основного метода делают обратный поворот всего кубика (возвращают сторону в первоначальное положение).
Еще есть методы helpMemory, swipeAnySideRight и swipeAnySideLeft. Они нужны для удобства и сокращения кода (создание вспомогательного массива и повороты внутри выбранной грани очень часто используются)

**Comment by gagarski** [comment]
> Метод rotationMain (теперь public)

Допустим вы (или кто-то ещё) хочет написать программу, которая использует ваш класс (не в вашей функции `main`, а снаружи) и сделать следующее:
 - создать кубик;
 - перемешать его;
 - повернуть два слоя верхних слоя верхней грани по часовой стрелке (кстати, направления "по часовой стрелке" и "против часовой стрелки" в данном случае выглядят понятнее);
 - повернуть один слой левой грани против часовой стрелки;
 - повернуть кубик задней гранью вперёд;
 - напечатать состояние.

Можно ли сейчас так сделать?

Хотелось бы, чтобы любой программист, использующий  класс "Кубик" мог сделать так (может быть не в точности, но с настолько же понятным интерфейсом):
```java
public static void main(String[] args) {
    AllSides cube = new AllSides();
    cube.shuffle();
    cube.rotate(Sides.TOP, Direction.CLOCKWISE, {0, 1} /* два слоя */);
    cube.rotate(Sides.LEFT, Direction.COUNTERCLOCKWISE, {0});
    cube.moveToFront(Sides.BACK);
    System.out.println(cube);
}
```

Метод `rotate` вы можете свести к поворотам всего кубика и вызову `rotateMain` (который таки вспомогательный метод).

Ещё раз: цель данного задания -- создать представление кубика Рубика для программиста, котоырй может использовать его при написании своих программ (так же как вы, например, используете стандартные классы вроде списков, Map, строк и т. д.).

**Comment by AlexanderKuptsov** [comment]
Добавил: главный метод rotate, метод moveToFront (делает любую сторону фронтальной), метод show (показывает состояние кубика)

**Comment by gagarski** [comment]
1. Не реализован алгоритм сборки кубика (см. утилиты)
2. Выбор граней для поворота в виде строки -- плохое решение: используйте список или массив.
3. Сравнивать строковое представление в тестах -- плохое решение, реализуйте `equals()` (и `hashCode()`) для кубика и испольуйте его. Можно их сгенерировать автоматически с помощью среды разработки.
4. Получение видимого состояния кубика снаружи -- тоже неотъемлемая часть любого класса. У вас это можно сделать только в виде строки. Сделайте метод получения цвета заданной ячейки заданной грани. Как минимум, появится больше простора для написания тестов.
